import { evaluateOffer, type DecisionRecord, type MerchantProfile, type Variant } from '@retailagentos/engine';

export type ShowcaseStoreId = 'fresh-corner' | 'thecustomhub';
export interface ShowcaseBuyer { marketRegion?: string; fulfillmentMode?: string; contextSource?: 'controlled_fixture' | 'verified_session' | 'unavailable' | 'not_required'; }
export interface ShowcaseCartLine { productId: string; quantity: number; }
export interface ShowcaseStorefront { id: ShowcaseStoreId; displayName: string; fixtureClassification: string; merchant: MerchantProfile; variants: Variant[]; catalogVersion: string; policyVersion: string; fulfillmentModes: string[]; substitutionsSupported: boolean; quoteSupported: boolean; memberPricingSupported: boolean; shopperContext: Required<ShowcaseBuyer>; scenarioExplanation: string; /** Canonical per-variant-id quantity unit for search results (e.g. "1 dozen", "900g loaf"). Sourced from the fixture, not guessed from a title substring. Falls back to "each" when a variant has no explicit entry. */ quantityUnits?: Record<string, string>; }
export interface ShowcaseGatewayInput { storefront: ShowcaseStorefront; storefrontSessionId: string; now: number; }
export interface CompactShowcaseDecision { productId: string; eligible: boolean; code: string; reasons: Array<{ code: string; severity: string; message: string }>; nextAction: string; }
export type PurchasePlanStatus = 'ELIGIBLE' | 'REPAIRABLE' | 'BLOCKED' | 'QUOTE_REQUIRED';
export interface ShowcaseRepair { repairId: string; title: string; changes: Array<{ field: string; from: string; to: string }>; tradeoffs: { priceDelta: number; currency: string; timingDelta: string }; resolves: string[]; introduces: string[]; resultingStatus: 'ELIGIBLE'; }
export interface PurchasePlanDecision { status: PurchasePlanStatus; code: string; decisionId: string; lines: ShowcaseCartLine[]; reasons: CompactShowcaseDecision['reasons']; allowedNextActions: Array<'find_valid_alternatives' | 'apply_plan_repair' | 'prepare_validated_cart' | 'request_quote'>; nextAction: string; provenance: { storefrontId: ShowcaseStoreId; storefrontSessionId: string; catalogVersion: string; policyVersion: string; inventoryAsOf: string; evaluatedAt: string; expiresAt: string }; alternatives: ShowcaseRepair[]; }
type CartResponse = { storefrontId: ShowcaseStoreId; storefrontSessionId: string; cart: { reference: string; revision: number; lines: Array<ShowcaseCartLine & { title: string; price: number }>; total: number; currency: string } | null; code: string; nextAction: string; decision?: PurchasePlanDecision; cartCreated: boolean; orderPlaced: false; checkoutAvailable: false; checkoutStarted: false };
type RepairResponse = { status: 'APPLIED'; repair: ShowcaseRepair; decision: PurchasePlanDecision; lines: ShowcaseCartLine[] };
type QuoteResponse = { storefrontId: ShowcaseStoreId; storefrontSessionId: string; requestReference: string; status: 'QUOTE_REQUESTED'; code: string; nextAction: string; fixedPrice: null; cartCreated: false; checkoutStarted: false; orderPlaced: false; merchantReviewRequired: true };
export interface ReviseCartLine extends ShowcaseCartLine { title?: string; unitPrice?: number; lineTotal?: number; }
export interface ReviseCartCart { reference: string; revision: number; lines: ReviseCartLine[]; total: number; currency: string; budget?: { amount: number; currency: string }; remainingBudget?: number; fulfillment?: string; }
export type ReviseCartStatus = 'REVISED' | 'WITHHELD' | 'REPAIR_REQUIRED' | 'QUOTE_REQUIRED';
export interface ReviseCartResponse { status: ReviseCartStatus; code: string; previousCartReference?: string; cart: ReviseCartCart | null; cartCreated: boolean; cartRevised: boolean; checkoutAvailable: false; checkoutStarted: false; orderPlaced: false; paymentInitiated: false; nextAction: string; decision?: PurchasePlanDecision }
interface StoredDecision { decision: PurchasePlanDecision; buyer: Required<ShowcaseBuyer>; budget?: { amount: number; currency: string }; substitutionsAllowed: boolean; requestedDeliveryWindow?: string; expiresAt: number; }
interface StoredCart { reference: string; revision: number; storefrontId: ShowcaseStoreId; storefrontSessionId: string; lines: ShowcaseCartLine[]; buyer: Required<ShowcaseBuyer>; budget?: { amount: number; currency: string }; substitutionsAllowed: boolean; requestedDeliveryWindow?: string; expiresAt: number; }
export interface ShowcaseStores { carts: Map<string, CartResponse>; repairs: Map<string, RepairResponse>; quotes: Map<string, QuoteResponse>; decisions: Map<string, StoredDecision>; cartsByReference: Map<string, StoredCart>; revisions: Map<string, { fingerprint: string; result: ReviseCartResponse }> }
const MAX_RESULTS = 12;

export class ShowcaseGateway {
  private readonly stores: ShowcaseStores;
  constructor(private readonly input: ShowcaseGatewayInput, stores?: ShowcaseStores) { this.stores = stores ?? { carts: new Map(), repairs: new Map(), quotes: new Map(), decisions: new Map(), cartsByReference: new Map(), revisions: new Map() }; }
  getStorefrontCapabilities() { const store = this.input.storefront; return { storefrontId: store.id, storefrontSessionId: this.input.storefrontSessionId, retailer: store.displayName, fixtureClassification: store.fixtureClassification, supportedFulfillmentModes: store.fulfillmentModes, substitutionsSupported: store.substitutionsSupported, memberPricingSupported: store.memberPricingSupported, memberPricingContextSource: 'unavailable', quotesSupported: store.quoteSupported, cartPreparationSupported: store.id === 'fresh-corner', cartRevisionSupported: store.id === 'fresh-corner', checkoutExposed: false, catalogVersion: store.catalogVersion, policyVersion: store.policyVersion, safeNextAction: 'Evaluate a shopping plan before preparing a cart.', scenarioExplanation: store.scenarioExplanation }; }
  searchProducts(query: string, buyer: ShowcaseBuyer = {}, limit = 6) { const needle = this.boundedString(query, 'INVALID_QUERY', 240).toLowerCase(); if (!Number.isInteger(limit) || limit < 1 || limit > MAX_RESULTS) throw new ShowcaseInputError('INVALID_LIMIT', 'Use a result limit between 1 and 12.'); const candidates = this.input.storefront.variants.filter((variant) => variant.title.toLowerCase().includes(needle) || variant.sku.toLowerCase().includes(needle)).slice(0, limit).map((variant) => { const decision = this.evaluate(variant, 1, this.buyer(buyer)); const stale = decision.reasons.some((reason) => reason.code === 'STOCK_STALE'); return { productId: variant.id, title: variant.title, quantityUnit: this.input.storefront.quantityUnits?.[variant.id] ?? 'each', displayPrice: stale || variant.callForPrice ? undefined : variant.basePrice, currency: variant.currency, inventoryFact: stale ? 'STOCK_STALE' : 'CURRENT', code: stale ? 'STOCK_STALE' : decision.code, selectionState: stale ? 'REVALIDATION_REQUIRED' : variant.callForPrice ? 'QUOTE_REQUIRED' : 'EVALUATE_REQUIRED', nextAction: stale ? 'Inventory is stale. Evaluate the plan; do not prepare a cart from search.' : 'Evaluate a shopping plan before action.', storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, catalogVersion: this.input.storefront.catalogVersion, policyVersion: this.input.storefront.policyVersion }; }); return { storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, candidates, code: 'SEARCH_COMPLETE', nextAction: candidates.length ? 'Evaluate a shopping plan before preparing a cart.' : 'No matching controlled fixture products were found.' }; }
  evaluateOffer(productId: string, quantity: number, buyer: ShowcaseBuyer = {}) { return this.evaluate(this.variant(productId), quantity, this.buyer(buyer)); }
  evaluatePurchasePlan(lines: ShowcaseCartLine[], buyer: ShowcaseBuyer = {}, options: { budget?: { amount: number; currency: string }; substitutionsAllowed?: boolean; requestedDeliveryWindow?: string; fulfillmentMode?: string } = {}): PurchasePlanDecision {
    this.validateLines(lines);
    // `fulfillmentMode` (how the order is fulfilled — e.g. this storefront's local-delivery mode)
    // and `requestedDeliveryWindow` (an actual requested deadline/window) are deliberately separate
    // inputs. A caller must never smuggle a fulfillment-mode phrase like "using local delivery" into
    // `requestedDeliveryWindow` — that historically caused a real native agent to mis-map the visible
    // mission prompt into an unverifiable delivery deadline and hit DELIVERY_WINDOW_UNSUPPORTED for a
    // scenario that should have reached STOCK_STALE/REPAIRABLE. An explicit `fulfillmentMode` always
    // takes precedence over the storefront's default context and is validated against the storefront's
    // advertised `fulfillmentModes` below (in `buyer()`).
    const context = this.buyer(options.fulfillmentMode !== undefined ? { ...buyer, fulfillmentMode: options.fulfillmentMode } : buyer);
    const decisions = lines.map((line) => this.evaluate(this.variant(line.productId), line.quantity, context)); const quote = decisions.find((item) => item.code === 'QUOTE_REQUIRED');
    // A requested delivery date is never invented as a retailer promise. For a fixed-price line this
    // fixture cannot safely verify a prose delivery window, so it stays blocked. For a quote-only line
    // the requested date is instead carried forward as a merchant-review requirement (below), so a
    // correctly behaving agent reaches QUOTE_REQUIRED rather than an incorrect delivery-window dead end.
    if (options.requestedDeliveryWindow && !quote) return this.storeDecision(this.decision(lines, 'BLOCKED', 'DELIVERY_WINDOW_UNSUPPORTED', [{ code: 'DELIVERY_WINDOW_UNSUPPORTED', severity: 'BLOCK', message: 'This controlled fixture cannot safely verify a prose delivery window for a fixed-price product. Use the documented fulfillment mode or remove the unsupported constraint.' }], []), context, options);
    const stale = decisions.find((item) => item.reasons.some((reason) => reason.code === 'STOCK_STALE')); const blocked = decisions.find((item) => !item.eligible); const overBudget = options.budget && this.total(lines) > options.budget.amount; const source = stale ?? blocked;
    const alternatives = source && options.substitutionsAllowed !== false ? this.repairs(lines, source, context) : [];
    const status: PurchasePlanStatus = quote ? 'QUOTE_REQUIRED' : overBudget ? 'BLOCKED' : source ? alternatives.length ? 'REPAIRABLE' : 'BLOCKED' : 'ELIGIBLE'; const code = quote?.code ?? (overBudget ? 'BUDGET_EXCEEDED' : stale?.reasons.find((reason) => reason.code === 'STOCK_STALE')?.code ?? source?.code ?? 'ELIGIBLE');
    const deliveryCondition = options.requestedDeliveryWindow && quote ? [{ code: 'DELIVERY_WINDOW_MERCHANT_CONFIRMATION_REQUIRED', severity: 'CONDITION', message: 'The requested delivery date has not been promised and must be confirmed during merchant review.' }] : [];
    const reasons = overBudget ? [{ code: 'BUDGET_EXCEEDED', severity: 'BLOCK', message: 'The evaluated plan exceeds the shopper budget.' }] : quote ? [...quote.reasons, ...deliveryCondition].slice(0, 4) : source?.reasons ?? decisions.flatMap((item) => item.reasons).slice(0, 4);
    return this.storeDecision(this.decision(lines, status, code, reasons, alternatives), context, options);
  }
  findValidAlternatives(lines: ShowcaseCartLine[], decisionId?: string) { const stored = this.requireDecision(decisionId, lines); return { storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, alternatives: stored.decision.alternatives, decisionId: stored.decision.decisionId, provenance: stored.decision.provenance }; }
  applyPlanRepair(lines: ShowcaseCartLine[], repairId: string, idempotencyKey: string, decisionId?: string): RepairResponse { const key = this.scopedKey('repair', idempotencyKey); const prior = this.stores.repairs.get(key); if (prior) return prior; const stored = this.requireDecision(decisionId, lines); const repair = stored.decision.alternatives.find((item) => item.repairId === repairId); if (!repair) throw new ShowcaseInputError('INVALID_REPAIR', 'Choose a currently valid repair.'); const repairedLines = lines.map((line) => line.productId === repair.changes[0]?.from ? { ...line, productId: repair.changes[0].to } : line); const response: RepairResponse = { status: 'APPLIED', repair, decision: this.evaluatePurchasePlan(repairedLines, stored.buyer, { budget: stored.budget, substitutionsAllowed: stored.substitutionsAllowed, requestedDeliveryWindow: stored.requestedDeliveryWindow }), lines: repairedLines }; this.stores.repairs.set(key, response); return response; }
  prepareCart(lines: ShowcaseCartLine[], idempotencyKey: string, decisionId?: string): CartResponse { const key = this.scopedKey('cart', idempotencyKey); const prior = this.stores.carts.get(key); if (prior) return prior; const stored = this.requireDecision(decisionId, lines); const reevaluated = this.evaluatePurchasePlan(lines, stored.buyer, { budget: stored.budget, substitutionsAllowed: stored.substitutionsAllowed, requestedDeliveryWindow: stored.requestedDeliveryWindow }); const reference = `demo-cart-${key.slice(-12)}`; const response: CartResponse = reevaluated.status !== 'ELIGIBLE' ? { storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, cart: null, code: reevaluated.code, nextAction: reevaluated.nextAction, decision: reevaluated, cartCreated: false, orderPlaced: false, checkoutAvailable: false, checkoutStarted: false } : { storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, cart: { reference, revision: 1, lines: lines.map((line) => ({ ...line, title: this.variant(line.productId).title, price: this.variant(line.productId).basePrice })), total: this.total(lines), currency: 'USD' }, code: 'CART_PREPARED', nextAction: 'Cart prepared for visible shopper review. Checkout is intentionally unavailable.', decision: reevaluated, cartCreated: true, orderPlaced: false, checkoutAvailable: false, checkoutStarted: false }; this.stores.carts.set(key, response); if (response.cart) this.stores.cartsByReference.set(reference, { reference, revision: 1, storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, lines, buyer: stored.buyer, budget: stored.budget, substitutionsAllowed: stored.substitutionsAllowed, requestedDeliveryWindow: stored.requestedDeliveryWindow, expiresAt: stored.expiresAt }); return response; }
  /**
   * Optional post-cart revision pipeline. Never edits the visible cart directly: it verifies the
   * cart reference/storefront/session/revision/expiry against trusted stored state, recovers the
   * original shopper constraints, re-evaluates the proposed final line set through RetailAgentOS,
   * and only replaces the review cart when the resulting decision is ELIGIBLE. Prices, budget,
   * fulfillment, and policy are always derived from trusted stored state — never from the request.
   */
  reviseCart(cartReference: string, expectedRevision: number, lines: ShowcaseCartLine[], idempotencyKey: string): ReviseCartResponse {
    this.validateLines(lines);
    if (!Number.isInteger(expectedRevision) || expectedRevision < 1) throw new ShowcaseInputError('INVALID_REVISION', 'Provide a positive expected cart revision.');
    if (typeof cartReference !== 'string' || !cartReference.trim() || cartReference.length > 200) throw new ShowcaseInputError('CART_NOT_FOUND', 'Provide a valid cart reference.');
    const key = this.scopedKey('revise', idempotencyKey);
    const fingerprint = JSON.stringify({ cartReference, expectedRevision, lines });
    const prior = this.stores.revisions.get(key);
    if (prior) { if (prior.fingerprint !== fingerprint) throw new ShowcaseInputError('IDEMPOTENCY_KEY_REUSED', 'This idempotency key was already used for a different revision request.'); return prior.result; }
    const stored = this.stores.cartsByReference.get(cartReference);
    if (!stored) throw new ShowcaseInputError('CART_NOT_FOUND', 'This cart reference is not currently valid.');
    if (stored.storefrontId !== this.input.storefront.id) throw new ShowcaseInputError('STOREFRONT_MISMATCH', 'This cart belongs to another storefront.');
    if (stored.storefrontSessionId !== this.input.storefrontSessionId) throw new ShowcaseInputError('CONTEXT_MISMATCH', 'This cart belongs to another storefront session.');
    if (stored.expiresAt < this.input.now) throw new ShowcaseInputError('CART_EXPIRED', 'This cart has expired. Prepare a new cart before revising it.');
    if (stored.revision !== expectedRevision) throw new ShowcaseInputError('CART_REVISION_CONFLICT', 'This cart changed since it was last read. Re-read the cart before revising it.');
    const reevaluated = this.evaluatePurchasePlan(lines, stored.buyer, { budget: stored.budget, substitutionsAllowed: stored.substitutionsAllowed, requestedDeliveryWindow: stored.requestedDeliveryWindow });
    let result: ReviseCartResponse;
    if (reevaluated.status === 'ELIGIBLE') {
      const nextRevision = stored.revision + 1; const total = this.total(lines);
      const remainingBudget = stored.budget ? Number((stored.budget.amount - total).toFixed(2)) : undefined;
      const cart: ReviseCartCart = { reference: stored.reference, revision: nextRevision, lines: lines.map((line) => { const variant = this.variant(line.productId); return { ...line, title: variant.title, unitPrice: variant.basePrice, lineTotal: Number((variant.basePrice * line.quantity).toFixed(2)) }; }), total, currency: 'USD', budget: stored.budget, remainingBudget, fulfillment: stored.buyer.fulfillmentMode.toUpperCase() };
      this.stores.cartsByReference.set(stored.reference, { ...stored, revision: nextRevision, lines });
      result = { status: 'REVISED', code: 'CART_REVISED', previousCartReference: stored.reference, cart, cartCreated: true, cartRevised: true, checkoutAvailable: false, checkoutStarted: false, orderPlaced: false, paymentInitiated: false, nextAction: 'Review the revised cart. Checkout remains unavailable.', decision: reevaluated };
    } else if (reevaluated.status === 'QUOTE_REQUIRED') {
      result = { status: 'QUOTE_REQUIRED', code: reevaluated.code, cart: null, cartCreated: false, cartRevised: false, checkoutAvailable: false, checkoutStarted: false, orderPlaced: false, paymentInitiated: false, nextAction: 'This revision requires a merchant quote. The existing valid cart was not changed.', decision: reevaluated };
    } else if (reevaluated.status === 'REPAIRABLE') {
      result = { status: 'REPAIR_REQUIRED', code: reevaluated.code, cart: null, cartCreated: false, cartRevised: false, checkoutAvailable: false, checkoutStarted: false, orderPlaced: false, paymentInitiated: false, nextAction: 'This revision needs a new merchant-valid repair and explicit shopper approval. The existing valid cart was not changed.', decision: reevaluated };
    } else {
      result = { status: 'WITHHELD', code: reevaluated.code, cart: null, cartCreated: false, cartRevised: false, checkoutAvailable: false, checkoutStarted: false, orderPlaced: false, paymentInitiated: false, nextAction: reevaluated.code === 'BUDGET_EXCEEDED' ? 'The requested revision exceeds the original budget. The existing valid cart was not changed.' : reevaluated.nextAction, decision: reevaluated };
    }
    this.stores.revisions.set(key, { fingerprint, result });
    return result;
  }
  requestQuote(request: { productId?: string; quantity: number; requirements: string; idempotencyKey: string }): QuoteResponse { const key = this.scopedKey('quote', request.idempotencyKey); const prior = this.stores.quotes.get(key); if (prior) return prior; if (!this.input.storefront.quoteSupported) throw new ShowcaseInputError('QUOTE_UNAVAILABLE', 'This storefront does not accept quote requests.'); if (!Number.isInteger(request.quantity) || request.quantity < 1 || request.quantity > 99999 || !request.requirements.trim() || request.requirements.length > 2000) throw new ShowcaseInputError('INVALID_QUOTE_REQUEST', 'Provide bounded quantity and requirements.'); if (request.productId && !this.variant(request.productId).callForPrice) throw new ShowcaseInputError('QUOTE_NOT_REQUIRED', 'This product has a fixed-price path.'); const response: QuoteResponse = { storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, requestReference: `demo-quote-${key.slice(-12)}`, status: 'QUOTE_REQUESTED', code: 'QUOTE_REQUESTED', nextAction: 'Merchant review is required before any price can be returned.', fixedPrice: null, cartCreated: false, checkoutStarted: false, orderPlaced: false, merchantReviewRequired: true }; this.stores.quotes.set(key, response); return response; }
  private decision(lines: ShowcaseCartLine[], status: PurchasePlanStatus, code: string, reasons: CompactShowcaseDecision['reasons'], alternatives: ShowcaseRepair[]): PurchasePlanDecision { const now = this.input.now; const allowed = status === 'ELIGIBLE' ? ['prepare_validated_cart'] : status === 'REPAIRABLE' ? ['find_valid_alternatives', 'apply_plan_repair'] : status === 'QUOTE_REQUIRED' ? ['request_quote'] : []; return { status, code, decisionId: `${this.input.storefront.id}:${this.input.storefrontSessionId}:${now}:${lines.map((line) => `${line.productId}-${line.quantity}`).join('_')}`, lines: lines.map((line) => ({ ...line })), reasons, allowedNextActions: allowed as PurchasePlanDecision['allowedNextActions'], nextAction: status === 'ELIGIBLE' ? 'Prepare a visible cart for shopper review.' : status === 'REPAIRABLE' ? 'Present the approved alternative and wait for shopper approval.' : status === 'QUOTE_REQUIRED' ? 'Submit requirements for merchant review. No fixed price or cart exists.' : 'No cart was created. Update the request or buyer context.', provenance: { storefrontId: this.input.storefront.id, storefrontSessionId: this.input.storefrontSessionId, catalogVersion: this.input.storefront.catalogVersion, policyVersion: this.input.storefront.policyVersion, inventoryAsOf: new Date(now).toISOString(), evaluatedAt: new Date(now).toISOString(), expiresAt: new Date(now + 60_000).toISOString() }, alternatives }; }
  private storeDecision(decision: PurchasePlanDecision, buyer: Required<ShowcaseBuyer>, options: { budget?: { amount: number; currency: string }; substitutionsAllowed?: boolean; requestedDeliveryWindow?: string }) { this.stores.decisions.set(decision.decisionId, { decision, buyer, budget: options.budget, substitutionsAllowed: options.substitutionsAllowed !== false, requestedDeliveryWindow: options.requestedDeliveryWindow, expiresAt: this.input.now + 60_000 }); return decision; }
  private requireDecision(decisionId: string | undefined, lines: ShowcaseCartLine[]) { if (!decisionId) throw new ShowcaseInputError('DECISION_MISMATCH', 'Evaluate the exact plan before taking this action.'); const stored = this.stores.decisions.get(decisionId); if (!stored || stored.expiresAt < this.input.now) throw new ShowcaseInputError('DECISION_EXPIRED', 'Re-evaluate the plan before taking this action.'); if (stored.decision.provenance.storefrontId !== this.input.storefront.id) throw new ShowcaseInputError('STOREFRONT_MISMATCH', 'This decision belongs to another storefront.'); if (stored.decision.provenance.storefrontSessionId !== this.input.storefrontSessionId) throw new ShowcaseInputError('CONTEXT_MISMATCH', 'This decision belongs to another storefront session.'); if (JSON.stringify(stored.decision.lines) !== JSON.stringify(lines)) throw new ShowcaseInputError('DECISION_MISMATCH', 'The plan changed; re-evaluate before taking this action.'); return stored; }
  private repairs(lines: ShowcaseCartLine[], source: CompactShowcaseDecision, buyer: Required<ShowcaseBuyer>) { const stale = lines.find((line) => line.productId === 'v_g_inv_002_1'); const replacement = this.input.storefront.variants.find((variant) => variant.id === 'v_fresh_cagefree_001'); if (!stale || !replacement || !source.reasons.some((reason) => reason.code === 'STOCK_STALE') || !this.evaluate(replacement, stale.quantity, buyer).eligible) return []; return [{ repairId: 'replace-stale-farm-eggs-with-cage-free-eggs', title: 'Replace Farm Eggs with Cage-Free Eggs, 12-pack', changes: [{ field: 'line.productId', from: stale.productId, to: replacement.id }], tradeoffs: { priceDelta: Number((replacement.basePrice - this.variant(stale.productId).basePrice).toFixed(2)), currency: replacement.currency, timingDelta: 'Fresh inventory; same local-delivery mode' }, resolves: ['STOCK_STALE'], introduces: [], resultingStatus: 'ELIGIBLE' as const }]; }
  private buyer(value: ShowcaseBuyer = {}): Required<ShowcaseBuyer> { const fallback = this.input.storefront.shopperContext; const mode = value.fulfillmentMode ?? fallback.fulfillmentMode; if (!this.input.storefront.fulfillmentModes.includes(mode)) throw new ShowcaseInputError('CONTEXT_MISMATCH', 'This fulfillment mode is not supported by the active storefront.'); return { marketRegion: value.marketRegion ?? fallback.marketRegion, fulfillmentMode: mode, contextSource: fallback.contextSource }; }
  private evaluate(variant: Variant, quantity: number, buyer: Required<ShowcaseBuyer>): CompactShowcaseDecision { if (!Number.isInteger(quantity) || quantity < 1 || quantity > 99999) throw new ShowcaseInputError('INVALID_QUANTITY', 'Use a whole quantity between 1 and 99,999.'); const record = evaluateOffer({ merchant: this.input.storefront.merchant, variant, quantity, context: { marketRegion: buyer.marketRegion, fulfillmentMode: buyer.fulfillmentMode as 'shipping' | 'pickup' | 'local_delivery' }, now: this.input.now }); return compact(record, variant.id); }
  private variant(id: string) { const product = this.input.storefront.variants.find((variant) => variant.id === id); if (!product) throw new ShowcaseInputError('PRODUCT_NOT_FOUND', 'Choose a product from the active controlled storefront catalog.'); return product; }
  private validateLines(lines: ShowcaseCartLine[]) { if (!Array.isArray(lines) || !lines.length || lines.length > 20) throw new ShowcaseInputError('INVALID_CART', 'Provide between one and twenty cart lines.'); lines.forEach((line) => { if (!line || typeof line.productId !== 'string' || line.productId.length > 120 || !Number.isInteger(line.quantity) || line.quantity < 1 || line.quantity > 99999) throw new ShowcaseInputError('INVALID_CART', 'Use bounded product IDs and whole quantities.'); }); }
  private scopedKey(operation: string, value: string) { if (typeof value !== 'string' || value.length < 8 || value.length > 160) throw new ShowcaseInputError('IDEMPOTENCY_KEY_REQUIRED', 'Provide an idempotency key between 8 and 160 characters.'); return `${this.input.storefront.id}:${this.input.storefrontSessionId}:${operation}:${value}`; }
  private boundedString(value: string, code: string, max: number) { if (typeof value !== 'string' || !value.trim() || value.length > max) throw new ShowcaseInputError(code, 'Provide a shorter valid request.'); return value.trim(); }
  private total(lines: ShowcaseCartLine[]) { return Number(lines.reduce((sum, line) => sum + this.variant(line.productId).basePrice * line.quantity, 0).toFixed(2)); }
}
export class ShowcaseInputError extends Error { constructor(readonly code: string, message: string) { super(message); } }
export function compact(record: DecisionRecord, productId: string): CompactShowcaseDecision { const reasons = record.reasons.slice(0, 4).map(({ code, severity, message }) => ({ code, severity, message: message.slice(0, 180) })); const stale = reasons.some((reason) => reason.code === 'STOCK_STALE'); const blocked = reasons.some((reason) => reason.severity === 'BLOCK'); const quote = reasons.some((reason) => reason.code === 'CALL_FOR_PRICE'); return { productId, eligible: !blocked && !quote && !stale, code: stale ? 'STOCK_STALE' : blocked ? reasons.find((reason) => reason.severity === 'BLOCK')?.code ?? 'OFFER_BLOCKED' : quote ? 'QUOTE_REQUIRED' : 'ELIGIBLE', reasons, nextAction: stale ? 'Inventory is stale; re-evaluate and choose a merchant-valid repair before cart preparation.' : blocked ? 'Adjust the shopper context or choose a different product.' : quote ? 'Collect requirements and request a merchant quote.' : 'Evaluate the full plan before preparing a cart.' }; }
