import { describe, expect, it, vi } from 'vitest';
import { createRetailAgentWebMcp, getToolsForState, getWebMcpToolSchema } from './index';
import type { PlanDecision, RetailAgentGateway, WebMcpToolDescriptor } from './types';

const decision = (status: PlanDecision['status']): PlanDecision => ({ status, code: status === 'REPAIRABLE' ? 'STOCK_STALE' : status, decisionId: 'plan-1', lines: [{ productId: 'eggs', quantity: 1 }], reasons: [], allowedNextActions: status === 'REPAIRABLE' ? ['find_valid_alternatives', 'apply_plan_repair'] : ['prepare_validated_cart'], nextAction: 'Next action.', provenance: { storefrontId: 'fresh-corner', storefrontSessionId: 'session-1', catalogVersion: 'c1', policyVersion: 'p1', inventoryAsOf: 'now', evaluatedAt: 'now', expiresAt: 'later' }, alternatives: status === 'REPAIRABLE' ? [{ repairId: 'repair-1', title: 'Fresh eggs', changes: [{ field: 'line.productId', from: 'eggs', to: 'fresh-eggs' }], tradeoffs: { priceDelta: 0.5, currency: 'USD', timingDelta: 'same window' }, resolves: ['STOCK_STALE'], introduces: [], resultingStatus: 'ELIGIBLE' }] : [] });
function gateway(): RetailAgentGateway { return { getStorefrontCapabilities: vi.fn(async () => ({ code: 'OK' })), searchCatalog: vi.fn(async () => ({ code: 'OK', candidates: [] })), evaluateShoppingPlan: vi.fn(async () => decision('REPAIRABLE')), findValidAlternatives: vi.fn(async () => ({ decisionId: 'plan-1', alternatives: decision('REPAIRABLE').alternatives })), applyPlanRepair: vi.fn(async () => ({ status: 'APPLIED' as const, repair: decision('REPAIRABLE').alternatives[0], decision: decision('ELIGIBLE'), lines: [{ productId: 'fresh-eggs', quantity: 1 }] })), prepareValidatedCart: vi.fn(async () => ({ cart: { reference: 'cart-1', lines: [], total: 0, currency: 'USD' }, code: 'CART_PREPARED', nextAction: 'Review.', checkoutAvailable: false as const, checkoutStarted: false as const })), requestQuote: vi.fn(async () => ({ requestReference: 'quote-1', status: 'QUOTE_REQUESTED' as const, code: 'QUOTE_REQUESTED', nextAction: 'Review.', fixedPrice: null, cartCreated: false as const, checkoutStarted: false as const, orderPlaced: false as const, merchantReviewRequired: true as const })) }; }
function setup(native = true) { const descriptors: WebMcpToolDescriptor[] = []; const context = { registerTool: vi.fn((tool: WebMcpToolDescriptor) => { descriptors.push(tool); }), getTools: () => descriptors.map((tool) => tool.name) }; const sdk = createRetailAgentWebMcp({ gateway: gateway(), storefront: { getBuyerContext: () => ({}), requestRepairApproval: async () => 'approved' }, adapter: { getModelContext: () => native ? context : undefined }, clock: () => 1 }); return { sdk, descriptors, context }; }

describe('RetailAgentOS WebMCP descriptors', () => {
  it('provides strict schemas and standard annotations for seven tools', () => { const names = ['get_storefront_capabilities', 'search_catalog', 'evaluate_shopping_plan', 'find_valid_alternatives', 'apply_plan_repair', 'prepare_validated_cart', 'request_quote'] as const; expect(names).toHaveLength(7); names.forEach((name) => expect(getWebMcpToolSchema(name)).toMatchObject({ type: 'object', additionalProperties: false })); });
  it('registers only base tools initially, then replaces phase tools after decision', async () => { const { sdk, descriptors, context } = setup(); const registration = await sdk.register(); expect(registration.registeredTools).toEqual(['get_storefront_capabilities', 'search_catalog', 'evaluate_shopping_plan']); await descriptors.find((tool) => tool.name === 'evaluate_shopping_plan')!.execute({ lines: [{ productId: 'eggs', quantity: 1 }] }, { signal: new AbortController().signal }); expect(registration.registeredTools).toEqual(expect.arrayContaining(['find_valid_alternatives', 'apply_plan_repair'])); expect(registration.registeredTools).not.toContain('prepare_validated_cart'); expect(context.registerTool).toHaveBeenCalledTimes(5); });
  it('uses execution signals, cleans registration signals, and falls back to replay without native registration', async () => { const { sdk, descriptors } = setup(); const registration = await sdk.register(); const controller = new AbortController(); await descriptors[0].execute({}, { signal: controller.signal }); registration.dispose(); expect(registration.registeredTools).toEqual([]); const replay = setup(false); const replayRegistration = await replay.sdk.register(); expect(replayRegistration.supported).toBe(false); expect(replayRegistration.getReplayTools()).toEqual(getToolsForState('initial')); });
  it('normalizes missing, empty, and already-aborted execution options without secondary signal errors', async () => { const { sdk, descriptors } = setup(); await sdk.register(); await expect(descriptors[0].execute({})).resolves.toMatchObject({ code: 'OK' }); await expect(descriptors[0].execute({}, {})).resolves.toMatchObject({ code: 'OK' }); const controller = new AbortController(); controller.abort(); await expect(descriptors[0].execute({}, { signal: controller.signal })).resolves.toMatchObject({ code: 'CANCELLED' }); });
  it('cleans a partial registration instead of claiming a native registry', async () => { let calls = 0; const context = { registerTool: vi.fn(() => { calls += 1; if (calls === 2) throw new Error('nope'); }) }; const sdk = createRetailAgentWebMcp({ gateway: gateway(), storefront: { getBuyerContext: () => ({}) }, adapter: { getModelContext: () => context } }); await expect(sdk.register()).rejects.toThrow('REGISTRATION_FAILED'); });
  it('defers phase-tool removal until after an executing repair returns', async () => { const { sdk, descriptors } = setup(); const registration = await sdk.register(); await descriptors.find((tool) => tool.name === 'evaluate_shopping_plan')!.execute({ lines: [{ productId: 'eggs', quantity: 1 }] }); const repair = descriptors.find((tool) => tool.name === 'apply_plan_repair')!; const result = await repair.execute({ decisionId: 'plan-1', repairId: 'repair-1', lines: [{ productId: 'eggs', quantity: 1 }], idempotencyKey: 'abcdefgh' }); expect(result).toMatchObject({ status: 'APPLIED' }); expect(registration.registeredTools).toContain('apply_plan_repair'); await registration.settleRegistry(); expect(registration.registeredTools).toContain('prepare_validated_cart'); expect(registration.registeredTools).not.toContain('apply_plan_repair'); });
  it('delegates quote work and preserves a null fixed price', async () => { const { sdk } = setup(false); const registration = await sdk.register(); const result = await registration.invoke('request_quote', { quantity: 25, requirements: 'Robotics shirts', idempotencyKey: 'abcdefgh' }); expect(result.fixedPrice).toBeNull(); });
  it('labels a guided invocation as replay even when a native model context exists', async () => {
    const events: string[] = []; const descriptors: WebMcpToolDescriptor[] = [];
    const sdk = createRetailAgentWebMcp({ gateway: gateway(), storefront: { getBuyerContext: () => ({}), onLifecycle: (event) => events.push(`${event.tool}:${event.lifecycle}:${event.source}`) }, adapter: { getModelContext: () => ({ registerTool: vi.fn((tool: WebMcpToolDescriptor) => { descriptors.push(tool); }) }) }, clock: () => 1 });
    const registration = await sdk.register();
    expect(registration.supported).toBe(true);
    await registration.invoke('get_storefront_capabilities', {});
    expect(events).toContain('get_storefront_capabilities:invoked:replay');
    expect(events.every((entry) => !entry.includes(':invoked:native'))).toBe(true);
  });
  it('labels a real native descriptor call as native, never mutated by a concurrent guided call', async () => {
    const events: string[] = []; const descriptors: WebMcpToolDescriptor[] = [];
    const sdk = createRetailAgentWebMcp({ gateway: gateway(), storefront: { getBuyerContext: () => ({}), onLifecycle: (event) => events.push(`${event.tool}:${event.lifecycle}:${event.source}`) }, adapter: { getModelContext: () => ({ registerTool: vi.fn((tool: WebMcpToolDescriptor) => { descriptors.push(tool); }) }) }, clock: () => 1 });
    const registration = await sdk.register();
    const nativeDescriptor = descriptors.find((tool) => tool.name === 'get_storefront_capabilities')!;
    // Simulate the real browser invoking the registered descriptor directly (no `source` option, as a
    // genuine WebMCP host would never set it) concurrently with a guided replay call.
    await Promise.all([nativeDescriptor.execute({}, { signal: new AbortController().signal }), registration.invoke('search_catalog', { query: 'eggs' })]);
    expect(events).toContain('get_storefront_capabilities:invoked:native');
    expect(events).toContain('search_catalog:invoked:replay');
  });
  it('returns equivalent commerce results for native and guided execution of the same descriptor', async () => {
    const { sdk, descriptors } = setup(true); await sdk.register();
    const capabilities = descriptors.find((tool) => tool.name === 'get_storefront_capabilities')!;
    const nativeResult = await capabilities.execute({});
    const replayResult = await capabilities.execute({}, { source: 'replay' });
    expect(nativeResult).toEqual(replayResult);
  });
});
