import { describe, expect, it, vi } from 'vitest';
import { createRetailAgentWebMcp, getWebMcpToolSchema } from './index';

const gateway = { searchProducts: vi.fn(async () => ({ candidates: [], code: 'OK', nextAction: 'Choose a product.' })), evaluateOffer: vi.fn(async () => ({ productId: 'shirt', eligible: true, code: 'ELIGIBLE', nextAction: 'Add it.', decision: { productId: 'shirt', eligible: true, code: 'ELIGIBLE', reasons: [], nextAction: 'Add it.' } })), prepareCart: vi.fn(async () => ({ cart: { reference: 'cart-1', lines: [{ productId: 'shirt', quantity: 1 }] }, code: 'CART_PREPARED', nextAction: 'Confirm checkout.', decisions: [] })), requestQuote: vi.fn(async () => ({ requestReference: 'quote-1', code: 'QUOTE_REQUESTED', nextAction: 'Merchant review required.', fixedPrice: null as null })) };
const storefront = { getBuyerContext: () => ({ marketRegion: 'US' }), prepareCart: vi.fn(), showProduct: vi.fn() };
function create(configured = true) { const registered: any[] = []; const modelContext = { registerTool: vi.fn((tool: any) => { registered.push(tool); }) }; return { registered, modelContext, sdk: createRetailAgentWebMcp({ config: { tenantId: 't1', enabledTools: ['search_products', 'evaluate_offer', 'prepare_cart', 'request_quote'], requireCheckoutConfirmation: true }, gateway, storefront, adapter: { getModelContext: () => configured ? modelContext : undefined } }) }; }
describe('RetailAgentOS WebMCP SDK', () => {
  it('uses stable schemas and no-ops when unsupported', async () => { expect(getWebMcpToolSchema('search_products')).toMatchObject({ type: 'object' }); const { sdk } = create(false); await expect(sdk.register()).resolves.toMatchObject({ supported: false, registeredTools: [] }); });
  it('registers configured tools and uses abort lifecycle for cleanup', async () => { const { sdk, registered } = create(); const registration = await sdk.register(); expect(registration.registeredTools).toEqual(['search_products', 'evaluate_offer', 'prepare_cart', 'request_quote']); expect(registered[0].annotations).toMatchObject({ readOnlyHint: true, untrustedContentHint: true }); registration.dispose(); await registered[0].execute({ query: 'shirt' }); expect((gateway.searchProducts as any).mock.calls.at(-1)?.[1]?.signal?.aborted).toBe(true); });
  it('delegates each merchant decision to the gateway and keeps quote price unset', async () => { const { sdk, registered } = create(); await sdk.register(); await registered.find((tool) => tool.name === 'evaluate_offer').execute({ productId: 'shirt', quantity: 1 }); await registered.find((tool) => tool.name === 'prepare_cart').execute({ lines: [{ productId: 'shirt', quantity: 1 }], idempotencyKey: 'abcdefgh' }); const quote = await registered.find((tool) => tool.name === 'request_quote').execute({ quantity: 25, requirements: 'robotics team shirts', idempotencyKey: 'abcdefgh' }); expect(gateway.evaluateOffer).toHaveBeenCalled(); expect(gateway.prepareCart).toHaveBeenCalled(); expect(quote.fixedPrice).toBeNull(); });
});
