// /evidence/conformance — the conformance scoreboard (SWP-5 / EVIDENCE-PLAN E4).
//
// Next.js 16 conventions used here (verified against node_modules/next/dist/docs):
//   - 01-app/01-getting-started/15-route-handlers.md: a GET Route Handler with
//     no per-request data can opt into `export const dynamic = 'force-static'`
//     to prerender at build time. The sibling `conformance.json/route.ts` does
//     exactly that; this page is a plain Server Component (also prerenderable,
//     no request-time APIs used) rendering the SAME data.ts module.
//   - A `route.ts` cannot share a segment with `page.tsx` — that's why the JSON
//     lives at the distinct `conformance.json/` segment, not inside this one.
//
// Every number on this page is generated by src/app/evidence/conformance/data.ts
// from the registry + golden fixtures + mock merchant manifests — nothing here
// is hand-typed. See data.ts's header comment for exact sources.

import Link from 'next/link';
import type { Metadata } from 'next';
import {
  REASON_CODE_INVENTORY,
  REASON_CODE_SUMMARY,
  ARCHETYPE_GRID,
  ARCHETYPE_SPEC_ORDER,
  PUBLISHED_SPECS,
  getConformancePayload,
} from './data';

export const metadata: Metadata = {
  title: 'Conformance scoreboard — Evidence | RetailAgentOS',
  description:
    'Every reason code declared by a registered evaluator, checked against the golden fixture suite, generated at build time — plus an archetype × spec coverage grid for the three mock merchants.',
};

const payload = getConformancePayload();

function CoverageBadge({ covered }: { covered: boolean }) {
  return covered ? (
    <span className="inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full border bg-emerald-50 text-emerald-700 border-emerald-200">
      ✅ covered
    </span>
  ) : (
    <span className="inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full border bg-red-50 text-red-700 border-red-200">
      🔴 uncovered
    </span>
  );
}

function ArchetypeCellBadge({
  cell,
}: {
  cell: (typeof ARCHETYPE_GRID)[number]['cells'][keyof (typeof ARCHETYPE_GRID)[number]['cells']];
}) {
  if (cell.exercised === null) {
    return <span className="text-xs text-slate-400 italic">not derived</span>;
  }
  if (cell.exercised) {
    return (
      <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700">
        ✅
        {cell.namespaces.length > 0 && (
          <span className="font-normal text-slate-400"> {cell.namespaces.length} ns</span>
        )}
      </span>
    );
  }
  return <span className="text-xs font-semibold text-slate-300">—</span>;
}

export default function ConformancePage() {
  const rowsBySpec = new Map<string, typeof REASON_CODE_INVENTORY>();
  for (const row of REASON_CODE_INVENTORY) {
    const list = rowsBySpec.get(row.specId) ?? [];
    list.push(row);
    rowsBySpec.set(row.specId, list);
  }

  return (
    <div className="min-h-screen bg-white">
      <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        {/* Header */}
        <div className="mb-10">
          <p className="text-sm font-semibold text-emerald-600 uppercase tracking-wider mb-3">
            Evidence · Conformance
          </p>
          <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 mb-4">
            The conformance scoreboard
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl leading-relaxed">
            Every reason code a registered evaluator can emit, checked against the committed
            golden fixture suite — generated at build time from{' '}
            <code className="text-sm">src/lib/extensions/registry.ts</code> and{' '}
            <code className="text-sm">golden.json</code>, not hand-typed. A new reason code
            without fixture coverage (and without a documented synthetic-only exception) shows
            up red here automatically.
          </p>
          <p className="mt-4 text-sm text-slate-500">
            Machine-readable: <Link href="/evidence/conformance.json" className="text-emerald-600 hover:underline">/evidence/conformance.json</Link>
            {' · '}
            <Link href="/evidence" className="text-emerald-600 hover:underline">← back to Evidence</Link>
          </p>
        </div>

        {/* Summary stats */}
        <section className="mb-12">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <Stat value={REASON_CODE_SUMMARY.total} label="Reason codes tracked" detail="Across RAOS-0001, 0002, 0005, 0007, 0008" />
            <Stat value={REASON_CODE_SUMMARY.covered} label="Covered" detail="Fixture-reachable or a documented synthetic exception" />
            <Stat
              value={REASON_CODE_SUMMARY.uncovered}
              label="Uncovered"
              detail="Would fail this scoreboard"
              tone={REASON_CODE_SUMMARY.uncovered > 0 ? 'bad' : 'good'}
            />
            <Stat value={REASON_CODE_SUMMARY.fixtureCoveredDirectly} label="Directly fixture-covered" detail={`${REASON_CODE_SUMMARY.syntheticExceptionOnly} more via a dedicated unit test`} />
          </div>
        </section>

        {/* Claim discipline note */}
        <section className="mb-12 rounded-xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-700 mb-1">What this page proves — and doesn&apos;t</p>
          <p>
            This scoreboard covers <strong>built specs only</strong>: RAOS-0000, 0001, 0002, 0005,
            0007, 0008, and 0013 pt 1 (Decision Trace). Planned specs (0003, 0004, 0006, 0009–0012,
            0013 pt 2, 0014+) emit no reason codes yet and are never shown as covered here — see{' '}
            <Link href="/specs" className="text-emerald-600 hover:underline">/specs</Link> for status.
            RAOS-0000 (foundations) and RAOS-0013 pt 1 (decision trace) emit no reason codes of
            their own, so they don&apos;t appear in the reason-code table below — they do appear in
            the archetype grid.
          </p>
        </section>

        {/* Reason code inventory, generated */}
        <section className="mb-14">
          <h2 className="text-xl font-bold text-slate-900 mb-1">Reason code inventory × fixture coverage</h2>
          <p className="text-sm text-slate-500 mb-6">
            Generated from every registered evaluator&apos;s <code>reasonCodes</code> declaration
            (plus RAOS-0008&apos;s centrally-attached trust codes), checked against{' '}
            <code>golden.json</code>.
          </p>

          <div className="space-y-8">
            {(['0001', '0002', '0005', '0007', '0008'] as const).map(specId => {
              const rows = rowsBySpec.get(specId) ?? [];
              const spec = PUBLISHED_SPECS[specId];
              return (
                <div key={specId} className="rounded-xl border border-slate-200 overflow-hidden">
                  <div className="bg-slate-50 px-4 py-3 border-b border-slate-200 flex flex-wrap items-baseline justify-between gap-2">
                    <span className="font-semibold text-slate-800">
                      RAOS-{specId} · {spec.title}
                    </span>
                    <span className="text-xs text-slate-400">
                      {rows.filter(r => r.covered).length}/{rows.length} covered
                    </span>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="text-left text-xs uppercase tracking-wide text-slate-400 border-b border-slate-100">
                          <th className="px-4 py-2 font-semibold">Reason code</th>
                          <th className="px-4 py-2 font-semibold">Source</th>
                          <th className="px-4 py-2 font-semibold">Status</th>
                          <th className="px-4 py-2 font-semibold">Note</th>
                        </tr>
                      </thead>
                      <tbody>
                        {rows.map(row => (
                          <tr key={row.code} className="border-b border-slate-50 last:border-0">
                            <td className="px-4 py-2.5 font-mono text-xs text-slate-800">{row.code}</td>
                            <td className="px-4 py-2.5 text-xs text-slate-500">
                              {row.sources.map(s => s.replace('com.os.retailagent.shopping.', '')).join(', ')}
                            </td>
                            <td className="px-4 py-2.5"><CoverageBadge covered={row.covered} /></td>
                            <td className="px-4 py-2.5 text-xs text-slate-500 max-w-md">
                              {row.fixtureCovered
                                ? 'Appears in at least one golden fixture entry.'
                                : row.syntheticException
                                  ? (
                                    <>
                                      Synthetic-only — <code className="text-[11px]">{row.syntheticException.testFile}</code>.{' '}
                                      {row.syntheticException.reason}
                                    </>
                                  )
                                  : 'No fixture coverage and no documented exception.'}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* Archetype coverage grid */}
        <section className="mb-14">
          <h2 className="text-xl font-bold text-slate-900 mb-1">Archetype × spec coverage</h2>
          <p className="text-sm text-slate-500 mb-6">
            Generated from each mock merchant&apos;s published manifest (<code>mockMerchants[].manifest.capabilities[]</code>)
            — the same data served at <code>/.well-known/ucp</code>. A cell is derived, not asserted;
            cells with no capability toggle to check are marked &quot;not derived&quot;.
          </p>
          <div className="overflow-x-auto rounded-xl border border-slate-200">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wide text-slate-400 border-b border-slate-100 bg-slate-50">
                  <th className="px-4 py-3 font-semibold">Merchant</th>
                  <th className="px-4 py-3 font-semibold">Headline tier</th>
                  {ARCHETYPE_SPEC_ORDER.map(specId => (
                    <th key={specId} className="px-4 py-3 font-semibold whitespace-nowrap">RAOS-{specId}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {ARCHETYPE_GRID.map(row => (
                  <tr key={row.merchantId} className="border-b border-slate-50 last:border-0">
                    <td className="px-4 py-3 font-medium text-slate-800 whitespace-nowrap">{row.merchantName}</td>
                    <td className="px-4 py-3 text-slate-500">{row.headlineTier}</td>
                    {ARCHETYPE_SPEC_ORDER.map(specId => (
                      <td key={specId} className="px-4 py-3">
                        <ArchetypeCellBadge cell={row.cells[specId]} />
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="text-xs text-slate-400 leading-relaxed border-t border-slate-100 pt-6">
          <p>
            Generated at build time from: {payload.generatedFrom.reasonCodeInventory.join('; ')};{' '}
            {payload.generatedFrom.fixtures}; {payload.generatedFrom.archetypeGrid}. Golden fixtures
            last generated {payload.goldenFixtureGeneratedAt}.
          </p>
        </section>
      </div>
    </div>
  );
}

function Stat({
  value,
  label,
  detail,
  tone,
}: {
  value: number;
  label: string;
  detail: string;
  tone?: 'good' | 'bad';
}) {
  const valueColor = tone === 'bad' ? 'text-red-600' : tone === 'good' ? 'text-emerald-600' : 'text-slate-900';
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50/60 p-4 flex flex-col">
      <span className={`text-2xl font-extrabold tabular-nums ${valueColor}`}>{value}</span>
      <span className="text-xs font-semibold text-slate-600 mt-1">{label}</span>
      <span className="text-[11px] text-slate-400 mt-1.5 leading-snug">{detail}</span>
    </div>
  );
}
